version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - requests
        - beautifulsoup4
        - lxml
